Update app.component.ts
bjornnorgaard/didecide pull request #2
Opened 2022-01-25 20:24 UTC by PandaColada

Nye retter, tak! =D

2022-01-25 22:39 UTC, bjornnorgaard requested changes

2022-01-25 22:39 UTC, bjornnorgaard commented on angular/src/app/app.component.ts
> +    'Scramled eggs',
Indrykningen sejler. Når alt på billedet herunder bliver grønt, kan den godkendes.
![image](https://user-images.githubusercontent.com/9103554/151071334-313043bd-32e4-4fad-8d90-21cf38715f3c.png)

2022-01-25 22:39 UTC, bjornnorgaard commented on angular/src/app/app.component.ts
> +	'Pølse, kebab eller kyllingemix',
Skaber det her ikke bare en ny udgave af samme problem?

2022-01-25 22:42 UTC, bjornnorgaard commented
Når du har lavet ændringerne og "resolvet" mine kommentarer, trykker du på "re-request review" som vist. Derfra godkender jeg den nok ;) 

![image](https://user-images.githubusercontent.com/9103554/151071966-7afcbcc9-0f2c-442c-ae1f-c47c7d786bed.png)

2022-01-26 06:15 UTC, PandaColada commented
Ah, vi snakkede godt om det, da jeg så preview på den inden jeg pull requestede, men inde i notepad++, hvor jeg redigerede det stod det rigtigt 😂 kigger på det senere, tak!
________________________________
From: Bjørn Nørgaard ***@***.***>
Sent: Tuesday, January 25, 2022 11:42:21 PM
To: bjornnorgaard/didecide ***@***.***>
Cc: PandaColada ***@***.***>; Author ***@***.***>
Subject: Re: [bjornnorgaard/didecide] Update app.component.ts (PR #2)


Når du har lavet ændringerne og "resolvet" mine kommentarer, trykker du på "re-request review" som vist. Derfra godkender jeg den nok ;)

[image]<https://user-images.githubusercontent.com/9103554/151071966-7afcbcc9-0f2c-442c-ae1f-c47c7d786bed.png>

—
Reply to this email directly, view it on GitHub<https://github.com/bjornnorgaard/didecide/pull/2#issuecomment-1021677191>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARB4LQYKGYMLRVZZD6YNN53UX4RM3ANCNFSM5MZIIGTA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-01-26 18:59 UTC, merged